UPGRADE_ITEMS = [
    "Ejderha Pulu",
    "Ejderha Pençesi",
    "Gri Boya",
    "Ay taşı",
    "Mitril",
    "Akik",
    "Ağır Kemerler",
    "Tanrı Çiçeği",
    "Ork Dişi",
    "Ork Disi+",
    "Beyaz İnci",
    "Mavi İnci",
    "Kan Kırmızı İnci",
    "İstridye",
    "Büyülü Tohum",
    "Mavi Kristal",
    "Su Kristali",
    "Şeytan Külü",
    "Kuvars Kumu",
    "Parmak Kemikleri",
    "Süt Şerbeti",
    "Ork Topuzu",
    "Ayı Ayak Derisi",
    "Ayı Ayak Derisi+",
    "Ayı Safrası",
    "Ayı Safrası+",
    "Yabani Ganimeti",
    "Yaprak",
    "Şeytan Hatırası",
    "Şeytan Hatırası+",
    "Şeytan Mücevheri",
    "Şeytan Mücevheri+",
    "Katil Buz Balina Boynuzu",
    "Buz Topu",
    "Buz Küresi+",
    "Buz Parçası",
    "Buz Parçası+",
    "Başlangıç El Kitabı",
    "Başlangıç El Kitabı+",
    "Saldırgan Kaplanın Dişi",
    "Bayrak",
    "Alev Yelesi",
    "Lanet Kitabı",
    "Lanet Kitabı+",
    "Kurbağa Bacağı",
    "Kurbağa Dili",
    "Yüz Kremi",
    "Kılçık",
    "Yaban Domuzu Dişi",
    "Çile",
    "Savaşçı Sembolü",
    "Ork Muskası",
    "Ork Muskası+",
    "Paslı Bıçak",
    "Kırmızı Domuz Kuyruğu Kurdele",
    "Yılan Derisi",
    "Yılan Kuyruğu",
    "Yılan Kuyruğu+",
    "Süs Eşyası",
    "Süslü Saç Tokası",
    "Yıpranmış Siyah Üniforma",
    "Siyah Üniforma+",
    "Domuz Burnu",
    "Shirken",
    "Shirken+",
    "Akrep İğnesi",
    "Akrep Kıskacı",
    "Akrep Kuyruğu",
    "Akrep Kuyruğu+",
    "Örümcek Yumurta Kesesi",
    "Örümceğin Zehir Kesesi",
    "Örümcek Gözleri",
    "Örümcek Bacakları",
    "Örümcek Ağı",
    "Değerli Taş Parçası",
    "Sargı Bezi",
    "Sargı Bezi+",
    "Kırık Zırh Parçası",
    "Kaplan Postu",
    "Kaplan Pençesi",
    "Bilinmeyen İlaç",
    "Bilinmeyen İlaç+",
    "Bilinmeyen Tılsım",
    "Bilinmeyen Tılsım+",
    "Beyaz Domuz Kuyruğu Kurdele",
    "Beyaz Domuz Kuyruğu Kurdele+",
    "Beyaz Kaplan Postu",
    "Kurt Postu",
    "Kurt Postu+",
    "Kurt Pençesi",
    "Kurt Pençesi+",
    "Yeti Postu",
    "Yeti Postu+",
    "Kırık Porselen",
]
